### PR TITLE
nzbget archive update(s)

### PR DESCRIPTION
**Pull request by Morgon**
Project moved to GitHub; reflecting that in the archive URL.
Updated project to most recent, 16.3.

### CODE REVIEW

**Comment by gehan** [comment]
Is it actually as simple as this to get 16.3 working?

**Comment by ricardopadilha** [comment]
Not really. This does not mean that it will compile, or that it will run. Also, these other files need to be updated:
- https://github.com/droboports/nzbget/blob/master/src/dest/service.sh#L10
- https://github.com/droboports/nzbget/blob/master/src/dest/www/includes/variables.php#L4
- https://github.com/droboports/nzbget/blob/master/src/dest/www/includes/changelog.php

**Comment by ricardopadilha** [comment]
With that being said, I appreciate the effort. I'll get back to nzbget at some point, since I use it myself everyday. Unfortunately I have been quite busy in the recent months with no sign of getting less busy any time soon, so it might take a while.

**Comment by gehan** [comment]
I don't mind having a stab.

If I forked this PR and updated those files - would that be the place to start?

If it doesn't compile though then I guess I'd just need an idea of what to do.

It should just be a matter of giving it a go and debugging I would have thought, but you've done it before so any help would be appreciated! I was also looking at updated transmission too..

**Comment by ricardopadilha** [comment]
> If I forked this PR and updated those files - would that be the place to start?

Yeah, that would be it.

> If it doesn't compile though then I guess I'd just need an idea of what to do.

The compilation logs will show everything. You can upload them to pastebin or something like that and I'll have a look.

> It should just be a matter of giving it a go and debugging I would have thought

Yeah, that is pretty much it. I recommend using https://github.com/droboports/docker-cross-compiler.

**Comment by gehan** [comment]
I've got this working with 16.4 - only had to change the path for openssl. I could have updated to 1.0.2g but wasn't sure where you got that patch from.

I build it and it's running fine for me on my drobo 5n!

https://github.com/droboports/nzbget/pull/2

**Comment by ricardopadilha** [comment]
Thanks for the PR.

**Comment by gehan** [comment]
no probs!

**Pull request closed without merging**
